### ISSUE TITLE
Trouble installing on Lassen

### ISSUE THREAD

**Issue by bzdjordje** [optimas-org/optimas#117]
Hello,
I have managed to install and run Optimas on Livermore's Quartz (CPU) cluster but have not had luck yet doing so on the Lassen (GPU) cluster. Below are the modules I am using, in conjunction with WarpX, as well as the output log for pip install.

Currently Loaded Modules:
  1) StdEnv (S)   2) cmake/3.23.1   3) gcc/11.2.1   4) spectrum-mpi/rolling-release   5) cuda/12.0.0   6) boost/1.70.0   7) python/3.8.2

[optimas_install_lassen.txt](https://github.com/optimas-org/optimas/files/12655501/optimas_install_lassen.txt)

Thank you,
Blagoje

**Comment by AngelFP** [comment]
It seems to fail when trying to build and install scikit-learn from a cached file (it looks quite similar to this issue https://github.com/scikit-learn/scikit-learn/issues/24604). Could you try to install optimas again with `pip install optimas --no-cache-dir`?

**Comment by bzdjordje** [comment]
@AngelFP Thank you for the response, returning to this now it unfortunately seems that I still get the same error with that flag, any other potential ideas?

**Comment by AngelFP** [comment]
Interesting. Could you share again the full output when using this flag? In principle it shouldn't be trying to use cached packages anymore.

**Comment by bzdjordje** [comment]
@AngelFP You can find it attached here:

[optimas_install_lassen_2.txt](https://github.com/optimas-org/optimas/files/12908509/optimas_install_lassen_2.txt)

**Comment by AngelFP** [comment]
Thanks for sharing. It looks like LLNL is using it's own repository for Python packages (https://hpc.llnl.gov/technical-bulletins/bulletin-556) that serves already as a cache (that's why the `--no-cache-dir` flag is not being effective there). For some reason, the `scikit-learn` package in this repository is a `.tar.gz` file instead of a built python wheel. I think we could try to bypass this by installing forcing pip to install directly the wheel we want from PyPI.

You could try this by installing `scikit-learn` with
```
pip install https://files.pythonhosted.org/packages/91/4e/752fd6e0b6b828a9cd815941fb70723eaef5d0f4efd8b9b0eee7864b3511/scikit_learn-1.3.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```
and then trying again to install optimas normally with `pip install optimas`.

@shuds13 @jlnav @jmlarson1 Do you have any experience getting `libEnsemble` to run on Larssen?

**Comment by ax3l** [comment]
Without `ax`, this install also could get easier: #156

`scikit-learn`: I added instructions in https://warpx.readthedocs.io/en/latest/install/hpc/lassen.html#preparation

**Comment by AngelFP** [comment]
> Without `ax`, this install also could get easier: #156
> 
> `scikit-learn`: I added instructions in https://warpx.readthedocs.io/en/latest/install/hpc/lassen.html#preparation

Nice! The problem without `ax` is that then you can only use `optimas` for parameter scans, since all the optimizers depend on it.

**Comment by AngelFP** [comment]
Closing this issue, since I believe it is now solved in the WarpX docs.
